packages/common/components/blocks/content/list-item.marko
packages/common/components/blocks/content/list.marko
packages/common/components/blocks/content/magazine-cover.marko
packages/common/components/blocks/content/marko.json
packages/common/components/blocks/footer.marko
packages/common/components/blocks/head.marko
packages/common/components/blocks/header.marko
packages/common/components/elements/cta.marko
packages/common/components/layouts/ccnews-now.marko
packages/common/components/layouts/daily.marko
packages/common/components/layouts/health.marko
packages/common/components/layouts/hiring.marko
packages/common/components/layouts/marko.json
packages/common/components/layouts/military.marko
packages/common/components/layouts/weekly.marko
packages/common/graphql/fragments/latest-issue.js
tenants/all/config/brands.js
tenants/all/config/core.js
tenants/all/config/email-x.js
tenants/all/templates/ccnews-now.marko
tenants/all/templates/diverse-health.marko
tenants/all/templates/diverse-hiring.marko
tenants/all/templates/diverse-military.marko
tenants/all/templates/diverse-weekly-recap.marko

Layout and ad size adjustments

---

packages/common/components/blocks/content/list-item.marko
packages/common/components/blocks/content/list.marko
packages/common/components/elements/cta.marko

Poll section updates

---

packages/common/components/blocks/header.marko

Add newsletter name & date to header block for Diverse Daily

---

packages/common/components/blocks/daily-header.marko
packages/common/components/blocks/header.marko
packages/common/components/blocks/marko.json
packages/common/components/layouts/daily.marko
tenants/all/templates/diverse-daily.marko

Create header for Diverse Daily

---

tenants/all/config/brands.js

Remove social media icons from footer

---

packages/common/components/blocks/daily-header.marko

Add font weight to daily header

---

packages/common/components/elements/list-header.marko

Slight oversight on my part resulting in routes to /undefined which obviously don't work.

Fix accidentally broken # links.

---

packages/common/components/blocks/content/list-item.marko
packages/common/components/blocks/content/magazine-cover.marko
packages/common/components/blocks/content/no-image.marko
packages/common/components/blocks/content/section-specific/diverse-at-large-promo.marko
packages/common/components/blocks/content/section-specific/from-the-magazine.marko
packages/common/components/blocks/content/section-specific/on-the-move.marko
packages/common/components/blocks/content/section-specific/podcast.marko
packages/common/components/blocks/content/section-specific/poll.marko
packages/common/components/blocks/content/with-image.marko
packages/common/components/blocks/footer.marko
packages/common/components/blocks/header-with-date.marko
packages/common/components/elements/list-header.marko
packages/common/components/elements/logo.marko
packages/common/components/layouts/ccnews-now.marko
packages/common/components/layouts/daily.marko
packages/common/components/layouts/health.marko
packages/common/components/layouts/hiring.marko
packages/common/components/layouts/military.marko
packages/common/components/layouts/weekly.marko

Logo, magazine image, ad placement & display date adjustments

---

packages/common/components/blocks/header-with-date.marko
packages/common/components/layouts/daily.marko

Daily newsletter section layout adjustments and add name to date

---

packages/common/components/blocks/content/list-item.marko
packages/common/components/blocks/content/section-specific/on-the-move.marko
packages/common/components/layouts/daily.marko
packages/common/components/layouts/weekly.marko

Read more added to on-the-move & new-hires sections

---

packages/common/components/blocks/content/section-specific/on-the-move.marko
packages/common/components/blocks/content/with-image.marko
packages/common/components/layouts/ccnews-now.marko
packages/common/components/layouts/hiring.marko

On the Move & New Hires section

Add Read More to ccnews & hiring template

---

packages/common/components/blocks/content/list.marko
packages/common/components/layouts/hiring.marko

Update list-block to allow for correct placements of ads on hiring template

---

packages/common/components/blocks/footer.marko
packages/common/components/blocks/header-with-date.marko
packages/common/components/blocks/header.marko
tenants/all/config/brands.js
tenants/all/config/core.js

Before font-size increase:
Current font-size:

Increase date size & update footer subscribe link

---

packages/common/components/blocks/content/section-specific/on-the-move.marko

Adjust on-the-move image stylings

---

packages/common/components/blocks/hide-view-online.marko
packages/common/components/blocks/marko.json
packages/common/components/layouts/daily.marko
tenants/all/templates/diverse-daily.marko

Hide view online

---

packages/common/components/blocks/content/list.marko
packages/common/components/layouts/ccnews-now.marko
packages/common/components/layouts/daily.marko
packages/common/components/layouts/health.marko
packages/common/components/layouts/hiring.marko
packages/common/components/layouts/military.marko
packages/common/components/layouts/weekly.marko

4 stories scheduled:
3 stories scheduled:
5 or more stories scheduled:

Adjust ad slots for all layouts

---

packages/common/components/blocks/footer.marko

Remove crop on social media icons

---

tenants/all/config/brands.js
tenants/all/config/core.js

Update logos for Daily, Weekly, Hiring templates

---

packages/common/components/blocks/content/list-item.marko
packages/common/components/blocks/content/no-image.marko
packages/common/components/blocks/content/section-specific/diverse-at-large-promo.marko
packages/common/components/blocks/content/section-specific/from-the-magazine.marko
packages/common/components/blocks/content/section-specific/on-the-move.marko
packages/common/components/blocks/content/section-specific/podcast.marko
packages/common/components/blocks/content/section-specific/poll.marko
packages/common/components/blocks/content/with-image.marko

Update color to match new logo

---

docker-compose.yml
packages/common/components/layouts/daily.marko

Add 'Top Articles' section to daily newsletter

---

packages/common/components/layouts/daily.marko

Remove limit on Featured Stories section and adjust top stories blocks

---

packages/common/components/blocks/content/list.marko
packages/common/components/elements/list-subheader.marko
packages/common/components/elements/marko.json
packages/common/components/layouts/daily.marko

Create a subheader option and add to most read blocks

---

packages/common/components/blocks/content/list.marko
packages/common/components/elements/list-subheader.marko
packages/common/components/layouts/daily.marko

Adjust spacing and titles of Most Read Articles blocks

---

packages/common/components/blocks/content/list.marko

Remove e- from most read article in DAY_OF_WEEK newsletter heading

---

packages/common/components/layouts/ccnews-now.marko

Add Most Read Block, CCNews Now Newsletter

---

packages/common/components/blocks/content/list.marko

Adjust yesterdayOfWeek to only display Mon-Fri

---

packages/common/components/blocks/content/list.marko
packages/common/components/layouts/ccnews-now.marko
packages/common/components/layouts/daily.marko

Monday newsletter date:
Wednesday newsletter date:

Adjust header for daily vs 2 day a week sends
